title: generic-scratch3-add-costume
hero_image: images/banner.png
description: generic-scratch3-add-costume description
version: 4
listed: false
copyedit: false
last_tested: "2018-05-08"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
