---
title: اضافه کردن لباس های جدید در اسکرچ
hero_image: images/banner.png
description: به شبح لباس اضافه کنید
original_url:
theme: قرمز
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "اسکرچ"
site_areas:
steps:
  - 
    title: اضافه کردن لباس

